FROM python:slim-bullseye
WORKDIR /root

ARG API_PORT

# OS updates and base requirements for Webby application in general
RUN apt-get update
RUN apt-get install -y libssl-dev 
RUN apt-get install -y build-essential

# Python reqruiements for all of the Webby application
COPY requirements.txt /root
RUN pip3 install -r requirements.txt

# Tier container specific content
RUN apt-get install -y redis-server
ADD ./static /root/static
ADD ./templates /root/templates
COPY db_start.sh /root
COPY db.py /root
RUN chmod +x /root/db_start.sh

EXPOSE ${API_PORT}
CMD /root/db_start.sh