FROM python:slim-bullseye
WORKDIR /root

ARG APP_PORT

# OS updates and base requirements for Webby application in general
RUN apt-get update
RUN apt-get install -y libssl-dev 
RUN apt-get install -y build-essential

# Python reqruiements for all of the Webby application
COPY requirements.txt /root
RUN pip3 install -r requirements.txt

# Tier container specific content
ADD ./static /root/static
ADD ./templates /root/templates
COPY web.py /root

EXPOSE ${APP_PORT}
CMD python3 web.py